databases:
  - name: crud_ecommerce_db  
    plan: free               
    databaseName: crud_ecommerce
    user: crud_ecommerce

services:
  - type: web
    plan: free
    name: crud_ecommerce     
    runtime: python
    buildCommand: "cd peripheral_store_crud && ./build.sh"  # Cambio clave
    startCommand: "cd peripheral_store_crud && gunicorn crud_ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"  # Cambio clave
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crud_ecommerce_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true  
      - key: WEB_CONCURRENCY
        value: 4            
      - key: IS_RENDER
        value: "True"       
      - key: DJANGO_SETTINGS_MODULE
        value: "crud_ecommerce.settings.production"  
      - key: ALLOWED_HOSTS
        value: ".onrender.com"